import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { XIcon } from './icons';
export const DownloadConfirmationModal = ({ t, onClose, onConfirm, language, isDownloading, }) => {
    const languageMap = {
        en: 'English',
        da: 'Dansk',
        sv: 'Svenska',
    };
    const fullLanguageName = languageMap[language] || 'English';
    return (_jsx("div", { className: "fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-60 backdrop-blur-sm animate-fade-in no-print", role: "dialog", "aria-modal": "true", onClick: onClose, children: _jsxs("div", { className: "relative bg-white rounded-2xl shadow-2xl p-8 m-4 max-w-sm w-full animate-fade-in-up", onClick: e => e.stopPropagation(), children: [_jsx("button", { onClick: onClose, className: "absolute top-4 right-4 text-gray-400 hover:text-gray-600", "aria-label": "Close", disabled: isDownloading, children: _jsx(XIcon, { className: "h-6 w-6" }) }), _jsx("h3", { className: "text-xl font-bold text-gray-800 mb-4", children: t.downloadModal.title }), _jsx("p", { className: "text-gray-600 mb-6", children: t.downloadModal.message.replace('{language}', fullLanguageName) }), _jsxs("div", { className: "flex justify-end gap-3", children: [_jsx("button", { onClick: onClose, disabled: isDownloading, className: "px-4 py-2 rounded-lg bg-gray-200 text-gray-800 font-semibold hover:bg-gray-300 transition-colors disabled:opacity-50", children: t.downloadModal.cancel }), _jsx("button", { onClick: onConfirm, disabled: isDownloading, className: "px-4 py-2 rounded-lg bg-orange-600 text-white font-semibold hover:bg-orange-700 transition-colors disabled:opacity-50 disabled:cursor-wait w-32 text-center", children: isDownloading ? (_jsxs("div", { className: "flex items-center justify-center", children: [_jsxs("svg", { className: "animate-spin -ml-1 mr-2 h-5 w-5 text-white", xmlns: "http://www.w3.org/2000/svg", fill: "none", viewBox: "0 0 24 24", children: [_jsx("circle", { className: "opacity-25", cx: "12", cy: "12", r: "10", stroke: "currentColor", strokeWidth: "4" }), _jsx("path", { className: "opacity-75", fill: "currentColor", d: "M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" })] }), t.downloadModal.downloading] })) : (t.downloadModal.confirm) })] })] }) }));
};
